export const LOADING_RECIPE_LIST = 'LOADING_RECIPE_LIST';
export const LOADING_FAILED_RECIPE_LIST = 'LOADING_FAILED_RECIPE_LIST';
export const LOADED_RECIPE_LIST = 'LOADED_RECIPE_LIST';


export const LOADING_RECIPE_BY_MARGIN_TOP = 'LOADING_RECIPE_BY_MARGIN_TOP';
export const LOADING_FAILED_RECIPE_BY_MARGIN_TOP = 'LOADING_FAILED_RECIPE_BY_MARGIN_TOP';
export const LOADED_RECIPE_BY_MARGIN_TOP = 'LOADED_RECIPE_BY_MARGIN_TOP';

export const LOADING_RECIPE_BY_MARGIN_BOTTOM = 'LOADING_RECIPE_BY_MARGIN_BOTTOM';
export const LOADING_FAILED_RECIPE_BY_MARGIN_BOTTOM = 'LOADING_FAILED_RECIPE_BY_MARGIN_BOTTOM';
export const LOADED_RECIPE_BY_MARGIN_BOTTOM = 'LOADED_RECIPE_BY_MARGIN_BOTTOM';

export const LOADING_RECIPE_BY_FLUCTUATION = 'LOADING_RECIPE_BY_FLUCTUATION';
export const LOADING_FAILED_RECIPE_BY_FLUCTUATION = 'LOADING_FAILED_RECIPE_BY_FLUCTUATION';
export const LOADED_RECIPE_BY_FLUCTUATION  = 'LOADED_RECIPE_BY_FLUCTUATION';